esphome:
  name: prometheus
  friendly_name: Prometheus_Inverted_Dimmer

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "WCh9duAvxF3hpHWJAMsXhLMEblRwgtY8HCphYSm8GiY="

ota:
  - platform: esphome
    password: "4662fe250be84e74cf8a3c14ea83a99b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Prometheus Fallback Hotspot"
    password: "OTpu9XNYcBfM"

captive_portal:
    
switch:
  platform: gpio
  name: "Switch 1"
  pin: 4

output:
  - platform: ledc
    pin: GPIO5
    id: gpio_5
    inverted: True
    frequency: "1000Hz"

light:
  - platform: monochromatic
    output: gpio_5
    name: "ESP32 Dimmer"